#!/bin/bash
export TERM=xterm
unset SESSION_MANAGER
xrdb
xsetroot -solid MidnightBlue 
export XKL_XMODMAP_DISABLE=1
[ -x vncconfig ] && vncconfig -iconic 2>/dev/null &
fluxbox &
chmod +x /vplbdx/vpl_wexecution
/vplbdx/vpl_wexecution &> .std_output
if [ -s .std_output ] ; then
	if [ "$(command -v xterm)" != "" ] ; then
		xterm -T "std output" -bg white -fg red -e less .std_output
	else
		if [ "$(command -v x-terminal-emulator)" != "" ] ; then
			x-terminal-emulator -e less .std_output
		fi
	fi
fi
