FROM gblin/minivpl
LABEL maintainer="guillaume.blin@u-bordeaux.fr"
LABEL authors="Guillaume Blin and Corentin Abel Mercier"
RUN install_packages openjdk-8-jdk junit openjfx
RUN install_packages locales-all libva-glx1 

